### ISSUE TITLE
At least one JPA metamodel must be present!

### ISSUE THREAD

**Issue by lumiseven** [spring-guides/gs-accessing-data-rest#18]
the guides works fine for version 1.5.10.release;
but not work for starter-data-rest version 2.0.0.release when i try to test code by myself, got exception:
```
...
Caused by: java.lang.IllegalArgumentException: At least one JPA metamodel must be present!
...
```
and I've clone the bench upgrade-to-boot-2 then run the code but still not fine. 
resolved it by add 
`@EnableAutoConfiguration(exclude={JpaRepositoriesAutoConfiguration.class})`
in `Application.java`
and i'm find other solutions.

**Comment by wonderfulxin** [comment]
have  you solve this ？？
