### ISSUE TITLE
How to map the endpoints when Person and PersonRepository are on a different package?

### ISSUE THREAD

**Issue by fireflieslive** [spring-guides/gs-accessing-data-rest#6]
I got a 404 when I place the Person and PersonRepository files on a different packages. 
@ComponentScan doesn't give the solution. I have an existing @RestController with /login /test endpoints. Any help on what might be the cause?

**Comment by gregturn** [comment]
You need to back up and describe the changes you made against the guide so we can deduce where you are seeing your error and how it varies from the guide.
