### ISSUE TITLE
Confusing statement in the documentation

### ISSUE THREAD

**Issue by behrangsa** [spring-guides/gs-accessing-data-rest#7]
In the documentation it is mentioned that:

> Spring Data REST is a Spring MVC application. The `@Import(RepositoryRestMvcConfiguration.class)` annotation imports a collection of Spring MVC controllers, JSON converters, and other beans needed to provide a RESTful front end. These components link up to the Spring Data JPA backend.

However `@Import(RepositoryRestMvcConfiguration.class)` is not used anywhere in the sample app.

**Comment by gregturn** [comment]
Spring Boot has automated this piece. However the ref docs can't presume developer is using Boot. Guide should cover this.

**Comment by behrangsa** [comment]
Hi @gregturn,

The problem is that this paragraph does not have context. I think we can add some context to it like this (emphasis mine):

> Spring Data REST is a Spring MVC application. The `@Import(RepositoryRestMvcConfiguration.class)` annotation imports a collection of Spring MVC controllers, JSON converters, and other beans needed to provide a RESTful front end. These components link up to the Spring Data JPA backend. _**Using Spring Boot, this process is automated.**_

I am still not very happy with the above paragraph. IMHO, it needs to be expanded into two paragraphs:

* A paragraph that explains that without Spring Boot, the developer has to use that annotation to link up the Spring MVC and the Spring Data backend.
* And a second paragraph that explains that with Spring Boot, the process is automated.

**Comment by dsyer** [comment]
I didn't think it needed 2 paragraphs. See 25ca400.
