### ISSUE TITLE
How did you set the URL prefix to ""? By default it is "/data/" when I try it.

### ISSUE THREAD

**Issue by adam66** [spring-guides/gs-accessing-data-rest#9]
Sorry to complain but I wasted 2 days trying to figure out why I was only getting 404 from my tests with MockMvc and in-container. I set up my project with the defaults, I hardly changed anything, yet the URL to the webservices is prefixed with '/data/'. It would have saved a lot of frustration if you'd mentioned it.

**Comment by dsyer** [comment]
Sorry for the frustration, but I'm not following you. There are some tests in this project (maybe you noticed) and they don't use a context path. You must be doing something different (like setting the context path).

**Comment by adam66** [comment]
I copied your tests almost exactly with a few changes for entity names, and I expected the URL to have no context path (as you say) however it does - my context path is mysteriously '/data' although I can't find where this is set. I assume it is a spring-data-rest default. No?

**Comment by dsyer** [comment]
No.

**Comment by adam66** [comment]
Argh! I just did a text search of my whole codebase for "data" (as you can imagine there were quite a few hits) and discovered a team mate had inserted his config for spring-data-rest on an elasticsearch project into the base properties file grrrr!
 
spring.data.rest.basePath=/data

Sorry about the rant.
